create table if not exists public.clientes_cnpj (
    id bigint generated by default as identity primary key,
    cliente text not null,
    cidade text,
    endereco text,
    cnpj text unique,
    razao_social text,
    glid text,
    observacao text,
    data_cadastro timestamptz default now(),
    data_ultima_atualizacao timestamptz default now()
);

create table if not exists public.historico_alteracoes (
    id bigint generated by default as identity primary key,
    tabela text not null,
    registro_id text,
    campo text not null,
    usuario text default 'SISTEMA',
    data_hora timestamptz default now(),
    valor_antigo text,
    valor_novo text
);

create index if not exists idx_clientes_cnpj_cliente on public.clientes_cnpj using gin (to_tsvector('portuguese', coalesce(cliente, '')));
alter table public.clientes_cnpj add column if not exists glid text;

create index if not exists idx_clientes_cnpj_cnpj on public.clientes_cnpj (cnpj);
create index if not exists idx_historico_alteracoes_data on public.historico_alteracoes (data_hora desc);
